### ISSUE TITLE
Trackpad still partially active even when mouse is locked

### ISSUE THREAD

**Issue by ntcarver0** [jmdaweb/inputLock#2]
Even when I have the mouse locked, some input from my trackpad is sent through to Windows. I'd like to be able to block all input if possible so to prevent accidentally moving the cursor among other things. I'm running Windows 10Ver1909 (64-bit) build 18363.900 on a Dell XPS 15 7590.

**Comment by jmdaweb** [comment]
You can block all mouse activity from the add-on settings. However, when you enable the corresponding option, all clicks will be blocked, even those simulated with NVDA gestures.
If your trackpad includes additional functionality (certain gestures processed by the driver), that situation is out of my control, at least for now. Changing this behaviour would require working at a very low level.

**Comment by ntcarver0** [comment]
OK, thank you. I appreciate it.
