### ISSUE TITLE
Feature Request: Add touchpad lock

### ISSUE THREAD

**Issue by cary-rowen** [jmdaweb/inputLock#7]
Hi @jmdaweb 

Currently the add-on does not have a feature to lock the touchpad. It can only lock the mouse. 
I would like to add a feature to lock the touchpad to this add-on.
If you agree, I am willing to submit a PR.

Thanks

**Comment by jmdaweb** [comment]
If you know a way to do it, go ahead! This is a feature requested for years, so a pr will be very appreciated. Please @nvdaes, could you grant me write access on the nvdaaddons repo for this add-on? It will require translation updates once modified, and it's the only one I can't edit yet.

**Comment by nvdaes** [comment]
> could you grant me write access on the nvdaaddons repo for this add-on?

Done. You can accept my invitation.
